baseurl = "http://data.education/"
languageCode = "en-gb"
title = "Data Education"
theme = "hugo-cards"
paginate = 6

[params]
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/ningdata"
  github = ""
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "Ning"
     link = ""

